services:
  - type: web
    name: llm-document-processor
    env: python
    plan: starter
    buildCommand: pip install -r optimized_requirements.txt
    startCommand: python production_api.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    disk:
      name: cache-disk
      mountPath: /app/cache
      sizeGB: 1

