services:
  - type: web
    name: llm-document-api
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBEXmpzj2fCz_9nU4RnrCmW5aon1JmyjiI
      - key: PYTHON_VERSION
        value: 3.10
