# services:
#   - type: web
#     name: fastapi-insurance-app
#     runtime: python
#     buildCommand: |
#       pip install --no-cache-dir -r requirements.txt
#       python -c "import nltk; nltk.download('punkt')"  # If you need NLTK
#     startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT production_api:app
#     envVars:
#       - key: PORT
#         value: 8000
#       - key: GEMINI_API_KEY
#         value: AIzaSyBEXmpzj2fCz_9nU4RnrCmW5aon1JmyjiI
services:
  - type: web
    name: fastapi-insurance-app
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y \
        libmupdf-dev \
        python3-dev \
        pkg-config \
        build-essential \
        gcc \
        g++ \
        make \
        cmake \
        libfreetype6-dev \
        libharfbuzz-dev \
        libjbig2dec0-dev \
        libopenjp2-7-dev \
        libpng-dev \
        libtiff5-dev \
        libx11-dev \
        libxext-dev \
        libxrender-dev \
        libxrandr-dev \
        libxtst-dev \
        libxi-dev \
        zlib1g-dev
      export MU_PDF_USE_SYSTEM_LIBS=1
      export MU_PDF_BUILD_TYPE=release
      pip install --no-cache-dir --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true